import type { Metadata } from "next";
import { Inter, Merriweather, Poppins } from "next/font/google";
import { Navbar } from "../../Components/Navbar";
import "./globals.css";

const poppins = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});
const merriweather = Merriweather({
  weight: ["300", "400", "700", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className="3xl:pl-[400px] 3xl:pr-[400px] 4xl:pl-[700px] 4xl:pr-[700px] "
    >
      <body className={`${poppins.className}  `}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
