import type { Metadata } from "next";
import { Inter, Poppins } from "next/font/google";
import "../../globals.css";

import ActiveCore from "./page";

const inter = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="3xl:pl-[400px] 3xl:pr-[400px]">
      <body className={inter.className}>
        <ActiveCore />
      </body>
    </html>
  );
}
